name: CI

on:
  push:
    branches: [master]

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        py_version: [3.7, 3.8, 3.9, "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py_version }}
          architecture: x64
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - name: Build wheels - universal2
        run: |
          export MACOSX_DEPLOYMENT_TARGET=10.14
          rustup target add aarch64-apple-darwin
          pip install maturin
          maturin build --release --universal2 --out dist
      - name: Install built wheel - universal2
        run: |
          pip instal